---
- name: security | disallow root SSH access
  action: lineinfile dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
  notify: restart ssh

- name: security | set SSH port
  action: lineinfile dest=/etc/ssh/sshd_config regexp="^Port" line="Port {{ssh_port}}" state=present
  notify: restart ssh

- name: security | disallow password authentication
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
  notify: restart ssh

- name: security | allow pubkey authentication
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PubkeyAuthentication" line="PubkeyAuthentication yes" state=present
  notify: restart ssh

- name: security | remove DNS check
  lineinfile: dest=/etc/ssh/sshd_config regexp="^UseDNS" line="UseDNS no" state=present
  notify: restart ssh

- name: security | install fail2ban
  apt: pkg=fail2ban state=present
